apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-fed-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/onehok1/federal-observability-demo.git
    targetRevision: HEAD
    path: apps  # <- replace with the actual folder path in your repo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
