apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  chart: grafana-operator
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  version: 5.8.0