apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  version: 2.9.11